grep "<<<<<" -rIi --include=*.tex
grep "=====" -rIi --include=*.tex
grep ">>>>>" -rIi --include=*.tex
grep " we " -rIi --include=*.tex
grep " Pia " -rIi --include=*.tex
grep "quality assesment manager" -rIi --include=*.tex
grep " id " -ri --include=*.tex
grep " Id " -ri --include=*.tex
grep " Pc " -ri --include=*.tex
grep " pc " -ri --include=*.tex
grep "QMS consult" -ri --include=*.tex
grep "qms consult" -ri --include=*.tex
grep "QMS-Consult" -ri --include=*.tex
grep "qms-Consult" -ri --include=*.tex
grep "qms-consult" -ri --include=*.tex
grep "\\\\newline" -rIi --include=*.tex
grep -P '\d+\.\d+' -r --include=*.tex
#grep '\\\\' -rIi --include=*.tex
#grep "\\\\cite{[a-zA-Z0-9]*}\\s*\\\\cite{[a-zA-Z0-9]*}" -rI --include=*.tex
